# Generated by Django 3.2.5 on 2021-11-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('contact_details', models.CharField(max_length=100)),
                ('personal_statement', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('chess_experience_level', models.IntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Expert'), (3, 'Master')])),
                ('user_type', models.IntegerField(choices=[(0, 'Other'), (1, 'Applicant'), (2, 'Member'), (3, 'Officer'), (4, 'Club owner')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
