# Generated by Django 3.2.5 on 2021-12-13 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20211208_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='member_type',
            field=models.IntegerField(choices=[(0, 'Applicant'), (1, 'Member'), (2, 'Officer'), (3, 'Club owner')]),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('co_organisers', models.ManyToManyField(related_name='co_oped_tournaments', to='clubs.Membership')),
                ('organiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tournaments', to='clubs.membership')),
            ],
        ),
    ]
