# Generated by Django 3.2.5 on 2021-12-13 12:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_rename_applicant_amount_limit_tournament_participant_amount_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='organiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tournaments', to='clubs.membership'),
        ),
    ]
