# Generated by Django 3.2.5 on 2021-12-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_auto_20211213_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
