# Generated by Django 3.2.5 on 2021-12-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_auto_20211213_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
