# Generated by Django 3.2.5 on 2021-12-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_alter_tournament_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='concluded',
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='conclusion',
            field=models.IntegerField(choices=[(0, 'Draw'), (1, 'Player 1 wins'), (2, 'Player 2 wins')], default=None, null=True),
        ),
    ]
