# Generated by Django 3.2.5 on 2021-12-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_auto_20211214_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='tournament',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clubs.tournament'),
            preserve_default=False,
        ),
    ]
