# Generated by Django 3.2.5 on 2021-12-14 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_alter_participant_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_won', to='clubs.participant'),
        ),
    ]
