# Generated by Django 3.2.5 on 2021-12-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_alter_tournament_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
