# Generated by Django 3.2.5 on 2021-12-15 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_alter_tournament_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clubs.group'),
            preserve_default=False,
        ),
    ]
