# Generated by Django 3.2.5 on 2021-12-15 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0022_alter_tournamentmatch_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmatch',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.tournament'),
        ),
    ]
