# Generated by Django 3.2.5 on 2021-12-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0023_alter_tournamentmatch_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='winner',
        ),
        migrations.AddField(
            model_name='participant',
            name='win',
            field=models.BooleanField(default=False),
        ),
    ]
