# Generated by Django 3.2.5 on 2021-12-15 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0025_rename_win_participant_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='total_participants',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=2, message='Total number of group participants, can not be lower than 2.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participant_amount_limit',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=2, message='Total number of participants, can not be lower than 2.'), django.core.validators.MaxValueValidator(limit_value=96, message='Total number of participants, can not be greater than 96.')]),
        ),
    ]
