# Generated by Django 3.2.5 on 2021-12-15 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0026_auto_20211215_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='total_participants',
            new_name='total_participants_limit',
        ),
    ]
