# Generated by Django 3.2.5 on 2021-12-15 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0027_rename_total_participants_group_total_participants_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='co_organisers',
        ),
        migrations.CreateModel(
            name='Co_oped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.membership')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.tournament')),
            ],
        ),
    ]
