# Generated by Django 3.2.5 on 2021-12-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0028_auto_20211215_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='co_organisers',
            field=models.ManyToManyField(through='clubs.Co_oped', to='clubs.Membership'),
        ),
    ]
