# Generated by Django 3.2.5 on 2021-12-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0029_tournament_co_organisers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='co_organisers',
            field=models.ManyToManyField(related_name='co_oped_tournamets', through='clubs.Co_oped', to='clubs.Membership'),
        ),
    ]
