# Generated by Django 3.2.5 on 2021-12-17 03:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0035_alter_group_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Group number, can not be lower than 1.')]),
        ),
    ]
