# Generated by Django 3.2.5 on 2021-12-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0037_alter_tournamentmatch_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouping',
            options={'ordering': ['points_in_group']},
        ),
    ]
