# Generated by Django 3.2.5 on 2021-12-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0038_alter_grouping_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='participant_amount_limit',
            new_name='total_participants_limit',
        ),
    ]
